import { ReactNode } from "react";
import "./globals.css";
import { Metadata } from "next";

// TODO: finish manifest file
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#FFFFFF",
};

type RootLayoutProps = {
  children: ReactNode;
};

// Since we have a `not-found.tsx` page on the root, a layout file
// is required, even if it's just passing children through.
export default function RootLayout({ children }: RootLayoutProps) {
  return children;
}
